services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: postgres:16
    restart: always
    # user: postgres
    ports:
      - "5432:5432"
    networks:
        - mainnet
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: piush
      POSTGRES_DB: gorm-demo
      PGUSER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  pgdata:
    driver: local

networks:
  mainnet:
